import {
    Day6Part1,
    isArrayEqual,
} from '../../src/2024/day6';

describe('day6 tests', () => {
    describe('day6Part1 tests', () => {
        it('Should return the number of positions in the guard\'s patrol path', () => {
            const testInput = `
....#.....
.........#
..........
..#.......
.#.....#..
..........
.#..^.....
........#.
#.........
......#...`.trim();
            const day6Part1 = new Day6Part1(testInput);
            expect(day6Part1.positions).toBe(41);
        });

        it('Should correctly return the number of positions when exiting to the right', () => {
            const testInput = `
....#.....
..........
..........
..#.......
.#.....#..
..........
.#..^.....
........#.
#.........
......#...`.trim();
            const day6Part1 = new Day6Part1(testInput);
            expect(day6Part1.positions).toBe(11);
        });

        it('Should correctly return the number of positions when exiting to the top', () => {
            const testInput = `
....#.....
.........#
..........
..........
.#.....#..
..........
.#..^.....
........#.
#.........
......#...`.trim();
            const day6Part1 = new Day6Part1(testInput);
            expect(day6Part1.positions).toBe(26);
        });

        it('Should correctly return the number of positions when exiting to the left', () => {
            const testInput = `
....#.....
.........#
..........
..#.......
.#.....#..
..........
....^.....
........#.
#.........
......#...`.trim();
            const day6Part1 = new Day6Part1(testInput);
            expect(day6Part1.positions).toBe(22);
        });

        it('Should correctly return the number of positions when more than one obstacle to the bottom', () => {
            const testInput = `
....#.....
.........#
..........
..#.......
.#.....##.
..........
.#..^.....
........#.
#.........
......#...`.trim();
            const day6Part1 = new Day6Part1(testInput);
            expect(day6Part1.positions).toBe(19);
        });

        it('Should correctly return the number of positions when more than one obstacle to the left', () => {
            const testInput = `
....#.....
.........#
..........
..#.......
.#.....#..
..........
.#..^.#...
........#.
#.........
......#...`.trim();
            const day6Part1 = new Day6Part1(testInput);
            expect(day6Part1.positions).toBe(18);
        });

        it('Should correctly return the number of positions when more than one obstacle to the right', () => {
            const testInput = `
....#.....
.......#.#
..........
..#.......
.#.....#..
..........
.#..^.....
........#.
#.........
......#...`.trim();
            const day6Part1 = new Day6Part1(testInput);
            expect(day6Part1.positions).toBe(28);
        });
    });

    describe('isArrayEqual tests', () => {
        it('Should return true if both arrays have the same length and values', () => {
            expect(isArrayEqual([ 1, 3 ], [ 1, 3 ])).toBe(true);
        });

        it('Should return false if the arrays have different values', () => {
            expect(isArrayEqual([ 1, 3 ], [ 1, 2 ])).toBe(false);
        });

        it('Should return false if the arrays have different lengths', () => {
            expect(isArrayEqual([ 1, 3 ], [ 1, 2, 3 ])).toBe(false);
        });
    });
});