import {
    Day8Part1,
} from '../../src/2024/day8';

describe('day8 tests', () => {
    describe('Day8Part1 tests', () => {
        it('Should return the number of antiNodes in a given map', () => {
            const testInput = `
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`.trim();
            const day8Part1 = new Day8Part1(testInput);
            expect(day8Part1.antiNodes).toBe(14);
        });
    });
});